In [258]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier


In [257]:
!pip install xgboost

   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 786.5 kB/s eta 0:02:09
   ---------------------------------------- 0.5/101.7 MB 786.5 kB/s eta 0:02:09
   ---------------------------------------- 0.8/101.7 MB 650.7 kB/s eta 0:02:36
   ---------------------------------------- 0.8/101.7 MB 650.7 kB/s eta 0:02:36
   ---------------------------------------- 1.0/101.7 MB 675.3 kB/s eta 0:02:30
    --------------------------------------- 1.3/101.7 MB 723.3 kB/s eta 0:02:19
    --------------------------------------- 1.3/101.7 MB 723.3 kB/s eta 0:02:19
    ----------

In [273]:
lab04.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [271]:
lab04=pd.read_csv('titanic_by_unice (2).csv')
lab04.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [272]:
# we separate features and target
X=lab04.drop("Survived", axis=1)
y=lab04["Survived"]
lab04.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [194]:
# In First split we split to get first the training data from the whole dataset which is 70% of our dataset
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
# second split
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [224]:
X_train.isna().sum()

Pclass            0
Age               0
SibSp             0
Parch             0
Fare              0
Sex_male          0
Title_Col         0
Title_Countess    0
Title_Dr          0
Title_Lady        0
Title_Master      0
Title_Miss        0
Title_Mlle        0
Title_Mme         0
Title_Mr          0
Title_Mrs         0
Title_Ms          0
Title_Rev         0
Embarked_Q        0
Embarked_S        0
dtype: int64

In [225]:
(X_train.isna().sum()/len(X_train))*100

Pclass            0.0
Age               0.0
SibSp             0.0
Parch             0.0
Fare              0.0
Sex_male          0.0
Title_Col         0.0
Title_Countess    0.0
Title_Dr          0.0
Title_Lady        0.0
Title_Master      0.0
Title_Miss        0.0
Title_Mlle        0.0
Title_Mme         0.0
Title_Mr          0.0
Title_Mrs         0.0
Title_Ms          0.0
Title_Rev         0.0
Embarked_Q        0.0
Embarked_S        0.0
dtype: float64

In [197]:
#AGE
#Fit imputer on TRAIN only
imputer = SimpleImputer(strategy='median')
imputer.fit(X_train[['Age']])



,missing_values,nan
,strategy,'median'
,fill_value,None
,copy,True
,add_indicator,False
,keep_empty_features,False


In [198]:
#AGE
# Transform all datasets using TRAIN stats
X_train['Age'] = imputer.transform(X_train[['Age']])
X_val['Age'] = imputer.transform(X_val[['Age']])
X_test['Age'] = imputer.transform(X_test[['Age']])

In [199]:
#CABIN
#we have remove(drop) the colum of cabin from the dataset because it has very high missing values
X_train = X_train.drop('Cabin', axis=1)
X_val = X_val.drop('Cabin', axis=1)
X_test = X_test.drop('Cabin', axis=1)

In [200]:
X_train = pd.get_dummies(X_train, columns=['Sex'], drop_first=True)
X_val = pd.get_dummies(X_val, columns=['Sex'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['Sex'], drop_first=True)

In [201]:
X_train['Sex_male'] = X_train['Sex_male'].astype(int)
X_val['Sex_male'] = X_val['Sex_male'].astype(int)
X_test['Sex_male'] = X_test['Sex_male'].astype(int)

In [202]:
X_val = X_val.reindex(columns=X_train.columns, fill_value=0)
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [203]:
print(X_train.isnull().sum())

PassengerId    0
Pclass         0
Name           0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       1
Sex_male       0
dtype: int64


In [204]:
X_train.duplicated().sum()

np.int64(0)

In [205]:
cols_to_drop = ['Ticket', 'PassengerId']

X_train = X_train.drop(cols_to_drop, axis=1)
X_val = X_val.drop(cols_to_drop, axis=1)
X_test = X_test.drop(cols_to_drop, axis=1)

In [206]:
#we extract then drop the column name
def extract_title(df):
    df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.')
    return df

X_train = extract_title(X_train)
X_val = extract_title(X_val)
X_test = extract_title(X_test)

In [207]:
#Encode Title
X_train = pd.get_dummies(X_train, columns=['Title'], drop_first=True)
X_val = pd.get_dummies(X_val, columns=['Title'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['Title'], drop_first=True)

In [208]:
#the here we drop this column of name
X_train = X_train.drop(['Name'], axis=1)
X_val = X_val.drop(['Name'], axis=1)
X_test = X_test.drop(['Name'], axis=1)

In [209]:
X_train = pd.get_dummies(X_train, columns=['Embarked'], drop_first=True)
X_val = pd.get_dummies(X_val, columns=['Embarked'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['Embarked'], drop_first=True)

In [210]:
# in deal with embarked we fit it to val and test
X_val = X_val.reindex(columns=X_train.columns, fill_value=0)
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [211]:
bool_cols = X_train.select_dtypes(include='bool').columns

X_train[bool_cols] = X_train[bool_cols].astype(int)
X_val[bool_cols] = X_val[bool_cols].astype(int)
X_test[bool_cols] = X_test[bool_cols].astype(int)

In [212]:
print(X_train.isnull().sum().sum())
print(X_train.dtypes)

0
Pclass              int64
Age               float64
SibSp               int64
Parch               int64
Fare              float64
Sex_male            int64
Title_Col           int64
Title_Countess      int64
Title_Dr            int64
Title_Lady          int64
Title_Master        int64
Title_Miss          int64
Title_Mlle          int64
Title_Mme           int64
Title_Mr            int64
Title_Mrs           int64
Title_Ms            int64
Title_Rev           int64
Embarked_Q          int64
Embarked_S          int64
dtype: object


TRAINING STAGE

In [217]:
# TRAINING USING LOGISTIC
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [229]:
val_pred = model.predict(X_val)
test_pred = model.predict(X_test)

In [243]:
#here we predict on evaluation data and test the perfomance from the evaluation dataset
val_pred = model.predict(X_val)
print("Validation Accuracy:", accuracy_score(y_val, val_pred))
print(confusion_matrix(y_val, val_pred))
print(classification_report(y_val, val_pred))
print("ROC AUC:", roc_auc_score(y_val, val_pred))

Validation Accuracy: 0.8432835820895522
[[61  9]
 [12 52]]
              precision    recall  f1-score   support

           0       0.84      0.87      0.85        70
           1       0.85      0.81      0.83        64

    accuracy                           0.84       134
   macro avg       0.84      0.84      0.84       134
weighted avg       0.84      0.84      0.84       134

ROC AUC: 0.8419642857142857


In [242]:
#
y_prob = model.predict_proba(X_test)[:, 1]

# Try a lower threshold
threshold = 0.4
y_pred_new = (y_prob >= threshold).astype(int)

print("Test Accuracy:", accuracy_score(y_test, y_pred_new))
print(confusion_matrix(y_test, y_pred_new))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, test_pred))


Test Accuracy: 0.8059701492537313
[[71 16]
 [10 37]]
ROC AUC: 0.8469063340670091
              precision    recall  f1-score   support

           0       0.85      0.83      0.84        87
           1       0.69      0.72      0.71        47

    accuracy                           0.79       134
   macro avg       0.77      0.78      0.77       134
weighted avg       0.79      0.79      0.79       134



In [248]:
rf = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42)
rf.fit(X_train, y_train)

,n_estimators,200
,criterion,'gini'
,max_depth,5
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [247]:
y_pred = rf.predict(X_val)
y_prob = rf.predict_proba(X_val)[:, 1]

print("Validation Accuracy:", accuracy_score(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))
print("ROC AUC:", roc_auc_score(y_val, y_prob))

Validation Accuracy: 0.8432835820895522
[[65  5]
 [16 48]]
              precision    recall  f1-score   support

           0       0.80      0.93      0.86        70
           1       0.91      0.75      0.82        64

    accuracy                           0.84       134
   macro avg       0.85      0.84      0.84       134
weighted avg       0.85      0.84      0.84       134

ROC AUC: 0.9225446428571429


In [246]:
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

print(" Test Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))

Accuracy: 0.8059701492537313
[[78  9]
 [17 30]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86        87
           1       0.77      0.64      0.70        47

    accuracy                           0.81       134
   macro avg       0.80      0.77      0.78       134
weighted avg       0.80      0.81      0.80       134

ROC AUC: 0.8416483247737833


In [250]:
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)


,loss,'log_loss'
,learning_rate,0.1
,n_estimators,100
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,3
,min_impurity_decrease,0.0
,init,None


In [268]:
#Predict on validation set
y_pred = gb.predict(X_val)
y_prob = gb.predict_proba(X_val)[:, 1]

print("Validation Accuracy:", accuracy_score(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))
print("ROC AUC:", roc_auc_score(y_val, y_prob))

Validation Accuracy: 0.835820895522388
[[64  6]
 [16 48]]
              precision    recall  f1-score   support

           0       0.80      0.91      0.85        70
           1       0.89      0.75      0.81        64

    accuracy                           0.84       134
   macro avg       0.84      0.83      0.83       134
weighted avg       0.84      0.84      0.83       134

ROC AUC: 0.9170758928571427


In [267]:
y_pred = gb.predict(X_test)
y_prob = gb.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7985074626865671
ROC AUC: 0.830765468329665
[[75 12]
 [15 32]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.85        87
           1       0.73      0.68      0.70        47

    accuracy                           0.80       134
   macro avg       0.78      0.77      0.78       134
weighted avg       0.80      0.80      0.80       134



In [261]:
xgb = XGBClassifier(n_estimators=200,learning_rate=0.05,max_depth=4, random_state=42)
xgb.fit(X_train, y_train)

,objective,'binary:logistic'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,None
,device,None
,early_stopping_rounds,None
,enable_categorical,False
,eval_metric,None


In [269]:
y_pred = xgb.predict(X_val)
y_prob = xgb.predict_proba(X_val)[:, 1]

print("Validation Accuracy:", accuracy_score(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))
print("ROC AUC:", roc_auc_score(y_val, y_prob))

Validation Accuracy: 0.8432835820895522
[[65  5]
 [16 48]]
              precision    recall  f1-score   support

           0       0.80      0.93      0.86        70
           1       0.91      0.75      0.82        64

    accuracy                           0.84       134
   macro avg       0.85      0.84      0.84       134
weighted avg       0.85      0.84      0.84       134

ROC AUC: 0.9084821428571428


In [270]:
y_pred = xgb.predict(X_test)
y_prob = xgb.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7686567164179104
ROC AUC: 0.8262411347517731
[[72 15]
 [16 31]]
              precision    recall  f1-score   support

           0       0.82      0.83      0.82        87
           1       0.67      0.66      0.67        47

    accuracy                           0.77       134
   macro avg       0.75      0.74      0.74       134
weighted avg       0.77      0.77      0.77       134

